#!/bin/python3

import math
import os
import random
import re
import sys

def arrayManipulation(n, queries):
    arr = [0]*(n+1)
    current_sum = 0
    max_sum = 0
    
    for query in queries:
        arr[query[0]-1] += query[2]
        arr[query[1]] -= query[2]
        
    for val in arr:
        current_sum += val
        max_sum = max(max_sum, current_sum)
    return max_sum
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
