#!/bin/python3

import math
import os
import random
import re
import sys

def rotateLeft(d, arr):
    # for i in range(d):
    #     first_el = arr[0]
    #     for j in range(len(arr)-1):
    #         arr[j] = arr[j+1]
    #     arr[-1] = first_el
    
    # return arr
    
    e_rot = d % len(arr)
    arr = arr[e_rot:] + arr[:e_rot]
    return arr

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    d = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = rotateLeft(d, arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
